"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase";
import { NotificationPanel } from "./NotificationPanel";

export function ProfilePanel() {
  const [userId, setUserId] = useState(""); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [headline, setHeadline] = useState(""); const [organization, setOrganization] = useState(""); const [location, setLocation] = useState(""); const [website, setWebsite] = useState(""); const [bio, setBio] = useState(""); const [avatar, setAvatar] = useState(""); const [theme, setTheme] = useState("system"); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; const supabase = createClient(); void supabase.auth.getUser().then(async ({ data, error: userError }) => { if (!active) return; if (userError || !data.user) { setError("Your session has expired. Please sign in again."); return; } setUserId(data.user.id); setEmail(data.user.email ?? ""); const { data: profile } = await supabase.from("profiles").select("full_name,headline,organization,location,website,bio,avatar_url,theme_preference").eq("id", data.user.id).maybeSingle(); if (!active) return; setName(profile?.full_name ?? ""); setHeadline(profile?.headline ?? ""); setOrganization(profile?.organization ?? ""); setLocation(profile?.location ?? ""); setWebsite(profile?.website ?? ""); setBio(profile?.bio ?? ""); setAvatar(profile?.avatar_url ?? ""); setTheme(profile?.theme_preference ?? "system"); }); return () => { active = false; }; }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); const { error: saveError } = await createClient().from("profiles").update({ full_name: name.trim() || null, headline: headline.trim() || null, organization: organization.trim() || null, location: location.trim() || null, website: website.trim() || null, bio: bio.trim() || null, avatar_url: avatar.trim() || null, theme_preference: theme, updated_at: new Date().toISOString() }).eq("id", userId); if (saveError) setError(saveError.message); else { document.documentElement.dataset.theme = theme; window.localStorage.setItem("mic-theme", theme); setMessage("Profile updated."); } setBusy(false); }
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !userId) return; if (!file.type.startsWith("image/") || file.size > 4_000_000) { setError("Choose an image smaller than 4 MB."); return; } setBusy(true); setError(""); const supabase = createClient(); const path = `profiles/${userId}/${Date.now()}-${file.name.replace(/[^a-z0-9._-]/gi, "-")}`; const { error: uploadError } = await supabase.storage.from("mic-media").upload(path, file, { upsert: false, contentType: file.type }); if (uploadError) setError(uploadError.message); else { const { data } = supabase.storage.from("mic-media").getPublicUrl(path); setAvatar(data.publicUrl); setMessage("Profile picture uploaded. Save your profile to keep it."); } setBusy(false); }
  async function signOut() { await createClient().auth.signOut(); window.location.href = "/"; }
  return <div className="account-workspace"><div className="account-grid"><nav className="account-nav" aria-label="Account navigation"><a href="/profile">Profile</a><a href="/profile/saved">Saved library</a><a href="/profile/liked">Liked stories</a><a href="/profile">Personal settings</a></nav><section><p className="eyebrow">READER ACCOUNT</p><div className="account-heading-row"><div><h1 className="account-title">Your MIC profile.</h1><p className="account-muted">Make your place in the ecosystem clear.</p></div>{avatar ? <img className="account-avatar" src={avatar} alt="Your profile picture" /> : <div className="account-avatar account-avatar-placeholder" aria-hidden="true">{name.slice(0, 1).toUpperCase() || "M"}</div>}</div><form className="account-form" onSubmit={save}><label>Name<input value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" /></label><label>Headline<input value={headline} onChange={(event) => setHeadline(event.target.value)} placeholder="Founder, investor, builder…" /></label><div className="account-form-grid"><label>Organization<input value={organization} onChange={(event) => setOrganization(event.target.value)} /></label><label>Location<input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Dar es Salaam, Tanzania" /></label></div><label>Website<input type="url" value={website} onChange={(event) => setWebsite(event.target.value)} placeholder="https://…" /></label><label>Bio<textarea rows={5} value={bio} onChange={(event) => setBio(event.target.value)} placeholder="What are you building or looking for?" /></label><label>Profile picture<input type="file" accept="image/*" onChange={upload} /></label><label>Avatar URL<input type="url" value={avatar} onChange={(event) => setAvatar(event.target.value)} placeholder="https://…" /></label><label>Theme<select value={theme} onChange={(event) => setTheme(event.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-message" role="status">{message}</p>}<div className="admin-actions"><button className="primary-button" disabled={busy}>{busy ? "Saving…" : "Save profile"}</button><button type="button" className="engagement-button" onClick={() => void signOut()}>Sign out</button></div></form></section></div><NotificationPanel /></div>;
}
