"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase";

export function ProfilePanel() {
  const [userId, setUserId] = useState(""); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [bio, setBio] = useState(""); const [avatar, setAvatar] = useState(""); const [theme, setTheme] = useState("system"); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; const supabase = createClient(); void supabase.auth.getUser().then(async ({ data, error: userError }) => { if (!active) return; if (userError || !data.user) { setError("Your session has expired. Please sign in again."); return; } setUserId(data.user.id); setEmail(data.user.email ?? ""); const { data: profile } = await supabase.from("profiles").select("full_name,bio,avatar_url,theme_preference").eq("id", data.user.id).maybeSingle(); if (!active) return; setName(profile?.full_name ?? ""); setBio(profile?.bio ?? ""); setAvatar(profile?.avatar_url ?? ""); setTheme(profile?.theme_preference ?? "system"); }); return () => { active = false; }; }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); const { error: saveError } = await createClient().from("profiles").update({ full_name: name.trim() || null, bio: bio.trim() || null, avatar_url: avatar.trim() || null, theme_preference: theme, updated_at: new Date().toISOString() }).eq("id", userId); if (saveError) setError(saveError.message); else { document.documentElement.dataset.theme = theme; window.localStorage.setItem("mic-theme", theme); setMessage("Profile updated."); } setBusy(false); }
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !userId) return; if (!file.type.startsWith("image/") || file.size > 4_000_000) { setError("Choose an image smaller than 4 MB."); return; } setBusy(true); setError(""); const supabase = createClient(); const path = `profiles/${userId}/${Date.now()}-${file.name.replace(/[^a-z0-9._-]/gi, "-")}`; const { error: uploadError } = await supabase.storage.from("mic-media").upload(path, file, { upsert: false, contentType: file.type }); if (uploadError) setError(uploadError.message); else { const { data } = supabase.storage.from("mic-media").getPublicUrl(path); setAvatar(data.publicUrl); setMessage("Avatar uploaded. Save your profile to keep it."); } setBusy(false); }
  async function signOut() { await createClient().auth.signOut(); window.location.href = "/"; }
  return <div className="account-grid"><nav className="account-nav" aria-label="Account navigation"><a href="/profile">Profile</a><a href="/profile/saved">Saved library</a><a href="/profile/liked">Liked stories</a><a href="/profile/settings">Settings</a></nav><section><p className="eyebrow">READER ACCOUNT</p><h2>{email}</h2><form className="account-form" onSubmit={save}><label>Name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Bio<textarea rows={5} value={bio} onChange={(event) => setBio(event.target.value)} /></label><label>Avatar URL<input type="url" value={avatar} onChange={(event) => setAvatar(event.target.value)} placeholder="https://…" /></label><label>Upload profile picture<input type="file" accept="image/*" onChange={upload} /></label><label>Theme<select value={theme} onChange={(event) => setTheme(event.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-message" role="status">{message}</p>}<div className="admin-actions"><button className="primary-button" disabled={busy}>{busy ? "Saving…" : "Save profile"}</button><button type="button" className="engagement-button" onClick={() => void signOut()}>Sign out</button></div></form></section></div>;
}
