import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy — MIC Pulse",
  description: "How MIC Pulse handles account, profile, newsletter, and application information.",
};

export default function PrivacyPage() {
  return <main className="content-shell"><article className="article-shell article-content"><p className="eyebrow">MIC PULSE / LEGAL</p><h1 className="display display-lg">Privacy,<br /><span>without the fog.</span></h1><p className="article-excerpt">MIC Pulse collects only the information needed to operate reader accounts, receive requests, and improve the platform.</p><section className="article-body"><h2>Information you provide</h2><p>When you create an account, update a profile, subscribe to the newsletter, or submit an application, MIC Pulse may process the information in that form, including your name, email address, profile details, and the message you choose to provide.</p><h2>How information is used</h2><p>We use this information to authenticate your account, deliver requested product features, respond to applications or enquiries, maintain platform security, and understand how the service is used. We do not sell personal information.</p><h2>Profile visibility and uploads</h2><p>Profile content is intended for the reader workspace unless a feature clearly identifies it as public. Please do not upload sensitive personal information in profile images, URLs, or application messages.</p><h2>Service providers</h2><p>MIC Pulse uses service providers for hosting, database, authentication, and email delivery. They process information only as needed to provide those services and secure the platform.</p><h2>Your choices</h2><p>You can update your account profile or request help with account information by contacting <a href="mailto:hello@micpulse.co.tz">hello@micpulse.co.tz</a>. You may also unsubscribe from newsletter communications through the link in an email when one is provided.</p><h2>Updates</h2><p>We may update this notice as the service evolves. Material changes will be reflected on this page with an updated effective date.</p><p className="muted">Effective date: 24 August 2026</p></section></article></main>;
}
