"use client";

import Link from "next/link";
import { Search, UserRound, X, ArrowUpRight } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase";
import { ThemeToggle } from "./ThemeToggle";

const links = [["Business", "/business"], ["Technology", "/technology"], ["Markets", "/finance"], ["Opportunities", "/opportunities"], ["Founders", "/founders"]] as const;

export function GlobalHeader() {
  const pathname = usePathname(); const router = useRouter(); const [menuOpen, setMenuOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(""); const [signedIn, setSignedIn] = useState(false); const searchInput = useRef<HTMLInputElement>(null);
  useEffect(() => { let mounted = true; const supabase = createClient(); void supabase.auth.getUser().then(({ data }) => { if (mounted) setSignedIn(Boolean(data.user)); }); const { data: subscription } = supabase.auth.onAuthStateChange((_event, session) => { if (mounted) setSignedIn(Boolean(session?.user)); }); return () => { mounted = false; subscription.subscription.unsubscribe(); }; }, []);
  useEffect(() => { setMenuOpen(false); setSearchOpen(false); }, [pathname]);
  useEffect(() => { if (!searchOpen) return; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; searchInput.current?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") setSearchOpen(false); }; window.addEventListener("keydown", onKeyDown); return () => { document.body.style.overflow = previousOverflow; window.removeEventListener("keydown", onKeyDown); }; }, [searchOpen]);
  function submitSearch(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const value = query.trim(); if (!value) { searchInput.current?.focus(); return; } setSearchOpen(false); router.push(`/search?q=${encodeURIComponent(value)}`); }
  return <><header className={`site-header ${pathname === "/" ? "site-header-hero" : ""}`}><div className="site-header-inner"><Link className="brand-lockup" href="/" aria-label="MIC Pulse — Motivate, Innovate, Create"><span className="brand-mark">MIC<span>•</span></span><span className="brand-lockup-copy"><strong>MIC PULSE</strong><small>Motivate • Innovate • Create</small></span></Link><button className={`site-menu-button ${menuOpen ? "is-open" : ""}`} aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} aria-controls="primary-navigation" onClick={() => setMenuOpen((value) => !value)}><span /><span /></button><nav id="primary-navigation" className={`site-nav ${menuOpen ? "is-open" : ""}`} aria-label="Primary navigation">{links.map(([label, href]) => <Link key={href} className={pathname === href || pathname.startsWith(`${href}/`) ? "is-active" : ""} href={href}>{label}</Link>)}<button className={`site-search-link ${pathname === "/search" ? "is-active" : ""}`} type="button" onClick={() => setSearchOpen(true)} aria-haspopup="dialog" aria-expanded={searchOpen} aria-label="Open MIC Pulse search" title="Search MIC Pulse"><Search size={15} strokeWidth={1.6} aria-hidden="true" /><span>Search</span></button></nav><div className="site-header-actions"><ThemeToggle /><Link className="account-link" href={signedIn ? "/profile" : "/login"} aria-label={signedIn ? "Open your profile" : "Sign in to MIC Pulse"}>{signedIn ? <><UserRound size={15} strokeWidth={1.6} aria-hidden="true" /><span>Account</span></> : "Sign in"}</Link><Link className="site-header-cta" href="/#newsletter">Join MIC <span>↗</span></Link></div></div></header>{searchOpen && <div className="site-search-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setSearchOpen(false); }}><section className="site-search-dialog liquid-glass" role="dialog" aria-modal="true" aria-labelledby="site-search-title"><div className="site-search-dialog-top"><span className="eyebrow">MIC PULSE / SEARCH</span><button className="site-search-close" type="button" onClick={() => setSearchOpen(false)} aria-label="Close search"><X size={18} strokeWidth={1.5} /></button></div><h2 id="site-search-title">Find the signal.</h2><p>Search stories, companies, founders, events, and opportunities across the MIC network.</p><form className="site-search-form" role="search" onSubmit={submitSearch}><Search size={18} strokeWidth={1.5} aria-hidden="true" /><input ref={searchInput} value={query} onChange={(event) => setQuery(event.target.value)} type="search" placeholder="Topic, organization, or person" aria-label="Search MIC Pulse" autoComplete="off" /><button type="submit" aria-label="Submit search"><ArrowUpRight size={18} strokeWidth={1.5} /></button></form><Link className="site-search-archive" href="/search" onClick={() => setSearchOpen(false)}>Open the full archive <ArrowUpRight size={14} strokeWidth={1.5} /></Link></section></div>}</>;
}
