"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase";

type Application = { id: string; application_type: "founder" | "investor"; full_name: string; email: string; organization: string | null; website: string | null; stage: string | null; message: string; status: "pending" | "reviewing" | "approved" | "declined"; created_at: string };
type Role = "owner" | "admin" | "editor" | "author" | "reader";

export function ApplicationManager() {
  const [rows, setRows] = useState<Application[]>([]); const [role, setRole] = useState<Role | null>(null); const [filter, setFilter] = useState("all"); const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  async function load() { setBusy(true); setError(""); const supabase = createClient(); const { data: userData } = await supabase.auth.getUser(); if (!userData.user) { setBusy(false); return; } const [{ data: profile }, { data, error: loadError }] = await Promise.all([supabase.from("profiles").select("role").eq("id", userData.user.id).maybeSingle(), supabase.from("community_applications").select("id,application_type,full_name,email,organization,website,stage,message,status,created_at").order("created_at", { ascending: false }).limit(100)]); setRole((profile?.role as Role | null) ?? null); if (loadError) setError(loadError.message); else setRows((data ?? []) as Application[]); setBusy(false); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => filter === "all" ? rows : rows.filter((row) => row.status === filter), [filter, rows]);
  async function updateStatus(id: string, status: Application["status"]) { const previous = rows; setRows((current) => current.map((row) => row.id === id ? { ...row, status } : row)); const { error: updateError } = await createClient().from("community_applications").update({ status, updated_at: new Date().toISOString() }).eq("id", id); if (updateError) { setRows(previous); setError(updateError.message); } }
  return <main className="admin-shell"><header className="admin-header"><div><p className="eyebrow">MIC ADMIN / COMMUNITY</p><h1>Applications</h1><p>Review founder and investor requests connected to the MIC ecosystem.</p></div><button className="admin-button secondary" onClick={() => void load()}>Refresh</button></header><section className="admin-card"><div className="admin-toolbar"><select aria-label="Filter applications" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All applications</option><option value="pending">Pending</option><option value="reviewing">Reviewing</option><option value="approved">Approved</option><option value="declined">Declined</option></select><span>{filtered.length} applications</span></div>{error && <p className="admin-error" role="alert">{error}</p>}{busy ? <p>Loading applications…</p> : filtered.length ? <div className="application-admin-list">{filtered.map((row) => <article className="application-admin-item" key={row.id}><div className="application-admin-header"><div><span className="eyebrow">{row.application_type} · {new Date(row.created_at).toLocaleDateString("en-TZ", { dateStyle: "medium" })}</span><h2>{row.full_name}</h2><p>{row.organization ?? "Independent applicant"}{row.stage ? ` · ${row.stage}` : ""} · {row.email}</p></div>{role === "owner" || role === "admin" ? <select value={row.status} aria-label={`Status for ${row.full_name}`} onChange={(event) => void updateStatus(row.id, event.target.value as Application["status"])}><option value="pending">Pending</option><option value="reviewing">Reviewing</option><option value="approved">Approved</option><option value="declined">Declined</option></select> : <span className="status-badge">{row.status}</span>}</div><p>{row.message}</p>{row.website && <a className="text-link" href={row.website} target="_blank" rel="noreferrer">Open website ↗</a>}</article>)}</div> : <div className="empty-state"><h2>No applications in this view.</h2><p>New founder and investor requests will appear here after authenticated submission.</p></div>}</section></main>;
}
