"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase";

type MediaRow = { id: string; filename: string; public_url: string; storage_path: string; mime_type: string; created_at: string };

export function MediaLibrary() {
  const [items, setItems] = useState<MediaRow[]>([]); const [query, setQuery] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { const { data, error: loadError } = await createClient().from("media").select("id,filename,public_url,storage_path,mime_type,created_at").order("created_at", { ascending: false }); setItems((data ?? []) as MediaRow[]); if (loadError) setError(loadError.message); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter(item => item.filename.toLowerCase().includes(query.toLowerCase())), [items, query]);
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setError(""); const client = createClient(); const path = `${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const uploadResult = await client.storage.from("mic-media").upload(path, file, { upsert: false, contentType: file.type }); if (uploadResult.error) setError(uploadResult.error.message); else { const { data } = client.storage.from("mic-media").getPublicUrl(path); const { error: rowError } = await client.from("media").insert({ storage_path: path, public_url: data.publicUrl, filename: file.name, mime_type: file.type, size_bytes: file.size }); if (rowError) setError(rowError.message); else { setMessage("Uploaded."); await load(); } } setBusy(false); event.target.value = ""; }
  async function remove(item: MediaRow) { if (!window.confirm(`Delete ${item.filename}?`)) return; setBusy(true); await createClient().storage.from("mic-media").remove([item.storage_path]); const { error: rowError } = await createClient().from("media").delete().eq("id", item.id); if (rowError) setError(rowError.message); else await load(); setBusy(false); }
  return <main className="admin-shell"><header className="admin-header"><div><p className="eyebrow">ASSETS / MEDIA</p><h1>Media library</h1><p>Upload reusable images to Supabase Storage. Files are never stored as database base64.</p></div><label className="admin-button">{busy ? "Uploading…" : "Upload image ↗"}<input hidden type="file" accept="image/*" onChange={upload} disabled={busy} /></label></header><section className="admin-card"><div className="admin-toolbar"><input aria-label="Search media" placeholder="Search files…" value={query} onChange={event => setQuery(event.target.value)} /><span>{filtered.length} assets</span></div>{message && <p className="admin-success">{message}</p>}{error && <p className="admin-error">{error}</p>}<div className="media-grid">{filtered.map(item => <figure className="media-card" key={item.id}><img src={item.public_url} alt={item.filename} /><figcaption><strong>{item.filename}</strong><div className="admin-actions"><button className="text-link" onClick={() => void navigator.clipboard.writeText(item.public_url)}>Copy URL</button><button className="text-link danger-link" onClick={() => void remove(item)}>Delete</button></div></figcaption></figure>)}{!filtered.length && <div className="empty-state"><h2>No media yet.</h2><p>Upload the first image to begin building the shared library.</p></div>}</div></section></main>;
}
