"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase";

type Field = { key: string; label: string; type?: "text" | "url" | "number" | "textarea" };
type Row = Record<string, string | boolean | null> & { id: string; published?: boolean };

export function SimpleResourceManager({ table, title, eyebrow, description, fields }: { table: "companies" | "startups" | "founders" | "market_updates" | "pages"; title: string; eyebrow: string; description: string; fields: Field[] }) {
  const [rows, setRows] = useState<Row[]>([]); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<Row | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function load() { setBusy(true); const { data, error: loadError } = await createClient().from(table).select("*").order("created_at", { ascending: false }); setRows((data ?? []) as Row[]); if (loadError) setError(loadError.message); setBusy(false); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => rows.filter(row => JSON.stringify(row).toLowerCase().includes(query.toLowerCase())), [rows, query]);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); const payload: Record<string, string | boolean | null> = {}; fields.forEach(field => { const value = String(data.get(field.key) ?? "").trim(); payload[field.key] = value || null; }); payload.published = data.get("published") === "on"; const client = createClient(); const result = editing?.id ? await client.from(table).update(payload as never).eq("id", editing.id) : await client.from(table).insert(payload as never); if (result.error) setError(result.error.message); else { setEditing(null); await load(); } setBusy(false); }
  async function remove(id: string) { if (!window.confirm("Delete this record permanently?")) return; setBusy(true); const { error: deleteError } = await createClient().from(table).delete().eq("id", id); if (deleteError) setError(deleteError.message); else await load(); setBusy(false); }
  return <main className="admin-shell"><header className="admin-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div><button className="admin-button" onClick={() => setEditing({ id: "", published: false })}>New record</button></header><section className="admin-card"><div className="admin-toolbar"><input aria-label={`Search ${title}`} placeholder={`Search ${title.toLowerCase()}…`} value={query} onChange={event => setQuery(event.target.value)} /><span>{filtered.length} records</span></div>{error && <p className="admin-error">{error}</p>}{busy && !rows.length ? <p>Loading…</p> : filtered.length ? <div className="admin-list">{filtered.map(row => <div className="admin-list-item" key={row.id}><div><strong>{String(row.name ?? row.title ?? "Untitled")}</strong><span>{String(row.slug ?? row.country ?? row.metric ?? "")} · {row.published ? "Published" : "Draft"}</span></div><div className="admin-actions"><button className="text-link" onClick={() => setEditing(row)}>Edit</button><button className="text-link danger-link" onClick={() => void remove(row.id)}>Delete</button></div></div>)}</div> : <div className="empty-state"><h2>No records yet.</h2><p>Create the first record to connect this workspace to the public site.</p></div>}</section>{editing && <div className="admin-modal-backdrop"><form className="admin-card admin-form admin-modal" onSubmit={save}><div className="admin-row"><h2>{editing.id ? "Edit" : "New"} {title.slice(0, -1)}</h2><button type="button" className="text-link" onClick={() => setEditing(null)}>Close</button></div>{fields.map(field => <label key={field.key}>{field.label}{field.type === "textarea" ? <textarea name={field.key} rows={4} defaultValue={String(editing[field.key] ?? "")} /> : <input name={field.key} type={field.type ?? "text"} defaultValue={String(editing[field.key] ?? "")} />}</label>)}<label className="checkbox"><input type="checkbox" name="published" defaultChecked={Boolean(editing.published)} /> Published</label><div className="admin-row"><button type="button" className="admin-button secondary" onClick={() => setEditing(null)}>Cancel</button><button className="admin-button" disabled={busy}>{busy ? "Saving…" : "Save"}</button></div></form></div>}</main>;
}
